export const ADD_ING = "ADD_ING";
export const REMOVE_ING = "REMOVE_ING";
export const SET_ING = "SET_ING";
export const FETCH_ING_FAILED = "FETCH_ING_FAILED";

export const INIT_PURCHASE = "INIT_PURCHASE";
export const PURCHASE_START = "PURCHASE_START";
export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS";
export const PURCHASE_FAIL = "PURCHASE_FAIL";

export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
